name=Sensirion I2C SBN4x
version=2.0.0
author=Sensirion
maintainer=Sensirion
sentence=Library for the SBN4X sensor by Sensirion
paragraph=Enables you to use the SBN4X sensor via I2C.
url=https://github.com/Sensirion/arduino-i2c-sbn4x
category=Sensors
architectures=*
depends=Sensirion Core
includes=SensirionI2cSbn4x.h
