/*
 * THIS FILE IS AUTOMATICALLY GENERATED
 *
 * Generator:     sensirion-driver-generator 1.5.1
 * Product:       sbn4x
 * Model-Version: 2.0.0
 */
/*
 * Copyright (c) 2026, Sensirion AG
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * * Redistributions of source code must retain the above copyright notice, this
 *   list of conditions and the following disclaimer.
 *
 * * Redistributions in binary form must reproduce the above copyright notice,
 *   this list of conditions and the following disclaimer in the documentation
 *   and/or other materials provided with the distribution.
 *
 * * Neither the name of Sensirion AG nor the names of its
 *   contributors may be used to endorse or promote products derived from
 *   this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

#ifndef SENSIRIONI2CSBN4X_H
#define SENSIRIONI2CSBN4X_H

#include <SensirionCore.h>
#include <Wire.h>

#define SBN4X_I2C_ADDR_20 0x20

typedef enum {
    SBN4X_START_PERIODIC_MEASUREMENT_MODE_CMD_ID = 0x10,
    SBN4X_STOP_MEASUREMENT_CMD_ID = 0x104,
    SBN4X_READ_MEASUREMENTS_RAW_CMD_ID = 0x260,
    SBN4X_FORCE_O2_RECALIBRATION_CMD_ID = 0x300,
    SBN4X_START_FORCED_CO2_RECALIBRATION_CMD_ID = 0x507,
    SBN4X_GET_FORCED_CO2_RECALIBRATION_STATUS_CMD_ID = 0x511,
    SBN4X_GET_PRODUCT_TYPE_CMD_ID = 0xd002,
    SBN4X_GET_PRODUCT_NAME_CMD_ID = 0xd014,
    SBN4X_GET_ARTICLE_CODE_CMD_ID = 0xd025,
    SBN4X_GET_SERIAL_NUMBER_CMD_ID = 0xd033,
    SBN4X_GET_DEVICE_UID_CMD_ID = 0xd051,
    SBN4X_GET_VERSION_CMD_ID = 0xd100,
    SBN4X_READ_DEVICE_STATUS_CMD_ID = 0xd206,
    SBN4X_READ_AND_CLEAR_DEVICE_STATUS_CMD_ID = 0xd210,
    SBN4X_DEVICE_RESET_CMD_ID = 0xd304,
} SBN4xCmdId;

class SensirionI2cSbn4x {
  public:
    SensirionI2cSbn4x();
    /**
     * @brief Initializes the SBN4x class.
     *
     * @param i2cBus Arduino stream object to be used for communication.
     */
    void begin(TwoWire& i2cBus, uint8_t i2cAddress);

    /**
     * @brief Read the measured values of the sensor
     *
     * @param[out] measurementCounter The measurement counter is incremented
     * with each measurement in the periodic measurement mode. A counter value
     * of 0 indicates that no measurement has been taken so far. The measurement
     * counters can be used to disambiguate the data returned by the sensor.
     * @param[out] o2DryPercent The measured O₂ concentration
     * @param[out] co2DryPercent The measured CO₂ concentration
     * @param[out] respiratoryExchangeRatio The measured respiratory exchange
     * ratio (RER), dimensionless
     * @param[out] pressure The measured pressure in Pa
     *
     * @return error_code 0 on success, an error code otherwise.
     */
    int16_t readMeasurements(uint16_t& measurementCounter, float& o2DryPercent,
                             float& co2DryPercent,
                             float& respiratoryExchangeRatio, float& pressure);

    /**
     * @brief startPeriodicMeasurementMode
     *
     * Starts periodic measurement of O2, humidity, temperature, pressure and
     * CO2. After starting the measurement, it takes some time (~20ms) until the
     * first measurement results are available. The command 0x02  will return an
     * error 0x20  until the first results are available. This command is only
     * available in idle mode. If the device is already in any measure mode, or
     * the requested sampling rate is not supported, this command has no effect.
     *
     * @param[in] samplingRate Sampling rate of the measurement in [mHz]. The
     * actual sampling rate in Hz is the value divided by 1000. The only valid
     * sampling rate is 30 Hz (30000 mHz).
     *
     * @return error_code 0 on success, an error code otherwise.
     *
     * Example:
     * --------
     *
     * @code{.cpp}
     *
     *     int16_t localError = 0;
     *
     *     localError = sensor.startPeriodicMeasurementMode(30000);
     *     if (localError != NO_ERROR) {
     *         return;
     *     }
     *
     * @endcode
     *
     */
    int16_t startPeriodicMeasurementMode(uint32_t samplingRate);

    /**
     * @brief stopMeasurement
     *
     * Stops the measurement and returns to idle mode. The last measurement
     * results can still be read out, if available. If the device is already in
     * idle mode, this command has no effect.
     *
     * @return error_code 0 on success, an error code otherwise.
     */
    int16_t stopMeasurement(void);

    /**
     * @brief readMeasurementsRaw
     *
     * Read the measured values O2, CO2 and ambient conditions from the sensor.
     * Each set of measurements is identified by the measurement counter.
     *
     * @param[out] measurementCounter The measurement counter is incremented
     * with each measurement in the periodic measurement mode. A counter value
     * of 0 indicates that no measurement has been taken so far. The measurement
     * counters can be used to disambiguate the data returned by the sensor.
     * @param[out] o2DryPercent The O2 concentration in 1/256 % of the measured
     * gas when the humidity in the gas is compensated. In order to obtain the
     * O2 concentration in %, the value has to be divided by 256.
     * @param[out] cO2DryPercent The CO2 concentration in 1/256 % of the
     * measured gas. In order to obtain the CO2 concentration in %, the value
     * has to be divided by 256.
     * @param[out] respiratoryExchangeRatio Respiratory exchange ratio (RER),
     * dimensionless. The value is provided in 1/256 units. To obtain the RER as
     * a floating-point value, divide by 256.
     * @param[out] pressure The pressure 1/256 Pa. In order to obtain the
     * pressure in Pa, the value has to be divided by 256.
     *
     * @return error_code 0 on success, an error code otherwise.
     */
    int16_t readMeasurementsRaw(uint16_t& measurementCounter,
                                int16_t& o2DryPercent, int16_t& cO2DryPercent,
                                int16_t& respiratoryExchangeRatio,
                                uint32_t& pressure);

    /**
     * @brief forceO2Recalibration
     *
     * Force a recalibration of the O2 sensor. This command is executed in
     * measurement mode only. The measurement loop is interrupted until the
     * recalibration is done and the new calibration value is written to flash.
     * After this, the sensor resumes measuring using the updated configuration
     * value.
     *
     * @return error_code 0 on success, an error code otherwise.
     */
    int16_t forceO2Recalibration(void);

    /**
     * @brief startForcedCO2Recalibration
     *
     * Force a recalibration of the CO2 sensor. This command is executed only
     * when the sensor is in periodic mode. There is no measurement data
     * available until the recalibration is fully applied to the CO2 sensor.
     * After this, the sensor resumes measuring using the updated calibration
     * value.
     *
     * @return error_code 0 on success, an error code otherwise.
     */
    int16_t startForcedCO2Recalibration(void);

    /**
     * @brief getForcedCO2RecalibrationStatus
     *
     * Get the status of the forced recalibration. This function can be polled
     * after starting a forced CO2 recalibration. The returned value is 0xFFFF
     * as long as the forced recalibration is running, and changes to 0 if the
     * forced recalibration is completed.
     *
     * @param[out] forcedRecalibrationStatus Status of the forced recalibration.
     *
     * @return error_code 0 on success, an error code otherwise.
     */
    int16_t
    getForcedCO2RecalibrationStatus(uint16_t& forcedRecalibrationStatus);

    /**
     * @brief getProductType
     *
     * Gets the product type from the device.
     *
     * @param[out] productType Null-terminated string containing the product
     * type.
     *
     * @return error_code 0 on success, an error code otherwise.
     */
    int16_t getProductType(int8_t productType[], uint16_t productTypeSize);

    /**
     * @brief getProductName
     *
     * Gets the product name from the device.
     *
     * @param[out] productName Null-terminated ASCII string containing the
     * product name. Up to 32 characters can be read from the device.
     *
     * @return error_code 0 on success, an error code otherwise.
     */
    int16_t getProductName(int8_t productName[], uint16_t productNameSize);

    /**
     * @brief getArticleCode
     *
     * Gets the article code from the device.
     *
     * @param[out] articleCode Null-terminated ASCII string containing the
     * article code. Up to 32 characters can be read from the device.
     *
     * @return error_code 0 on success, an error code otherwise.
     */
    int16_t getArticleCode(int8_t articleCode[], uint16_t articleCodeSize);

    /**
     * @brief getSerialNumber
     *
     * Gets the serial number from the device.
     *
     * @param[out] serialNumber Null-terminated ASCII string containing the
     * serial number. Up to 32 characters can be read from the device.
     *
     * @return error_code 0 on success, an error code otherwise.
     */
    int16_t getSerialNumber(int8_t serialNumber[], uint16_t serialNumberSize);

    /**
     * @brief getDeviceUid
     *
     * Gets the device uid from the device.
     *
     * @param[out] deviceUid 96 bit unique microcontroller UID in binary format.
     *
     * @return error_code 0 on success, an error code otherwise.
     */
    int16_t getDeviceUid(uint8_t deviceUid[], uint16_t deviceUidSize);

    /**
     * @brief getVersion
     *
     * Gets the version information for the hardware, firmware and communication
     * protocol.
     *
     * @param[out] firmwareMajor Firmware major version number.
     * @param[out] firmwareMinor Firmware minor version number.
     * @param[out] firmwareDevelopFlag Firmware develop flag. False for released
     * firmware.
     * @param[out] hardwareMajor Hardware major version number.
     * @param[out] hardwareMinor Hardware minor version number.
     * @param[out] protocolMajor Protocol major version number.
     * @param[out] protocolMinor Protocol minor version number.
     * @param[out] padding Padding byte, ignore this.
     *
     * @return error_code 0 on success, an error code otherwise.
     */
    int16_t getVersion(uint8_t& firmwareMajor, uint8_t& firmwareMinor,
                       bool& firmwareDevelopFlag, uint8_t& hardwareMajor,
                       uint8_t& hardwareMinor, uint8_t& protocolMajor,
                       uint8_t& protocolMinor, uint8_t& padding);

    /**
     * @brief readDeviceStatus
     *
     * Reads the current device status. Use this command to get detailed
     * information about the device status. The device status is encoded in
     * flags. Each device status flag represents a single bit in a 32-bit
     * integer value. If more than one error is present, the device status
     * register value is the sum of the corresponding flag values. For details
     * about the available flags, refer to the device status flags
     * documentation.
     *
     * @param[out] deviceStatus Device status (32 flags as an integer value).
     * For details, please refer to the device status flags documentation.
     *
     * @note The status flags of type "Error" are sticky, i.e. they are not
     * cleared automatically even if the error condition no longer exists. So
     * they can only be cleared manually with the command 0xD210 "Read And Clear
     * Device Status" or with a device reset. All other flags are not sticky,
     * i.e. they are cleared automatically if the trigger condition disappears.
     *
     * @return error_code 0 on success, an error code otherwise.
     */
    int16_t readDeviceStatus(uint32_t& deviceStatus);

    /**
     * @brief readAndClearDeviceStatus
     *
     * Reads the current device status (like command 0xD206 "Read Device
     * Status") and afterwards clears all flags.
     *
     * @param[out] deviceStatus Device status (32 flags as an integer value)
     * **before** clearing it. For details, please refer to the device status
     * flags documentation.
     *
     * @return error_code 0 on success, an error code otherwise.
     */
    int16_t readAndClearDeviceStatus(uint32_t& deviceStatus);

    /**
     * @brief deviceReset
     *
     * Executes a reset on the device. This has the same effect as a power
     * cycle.
     *
     * @return error_code 0 on success, an error code otherwise.
     */
    int16_t deviceReset(void);

    /**
     * @brief signalI16ToFloat
     *
     * @param[in] value
     *
     * @return Return the scaled int16_t value as unscaled floating point value.
     */
    static float signalI16ToFloat(int16_t value);

    /**
     * @brief signalU32ToFloat
     *
     * @param[in] value
     *
     * @return Return the scaled uint32_t value as unscaled floating point
     * value.
     */
    static float signalU32ToFloat(uint32_t value);

  private:
    TwoWire* _i2cBus = nullptr;
    uint8_t _i2cAddress = 0;
};

#endif  // SENSIRIONI2CSBN4X_H