/*
 * THIS FILE IS AUTOMATICALLY GENERATED
 *
 * Generator:     sensirion-driver-generator 1.3.4
 * Product:       sbn4x
 * Model-Version: 1.0.0
 */
/*
 * Copyright (c) 2025, Sensirion AG
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * * Redistributions of source code must retain the above copyright notice, this
 *   list of conditions and the following disclaimer.
 *
 * * Redistributions in binary form must reproduce the above copyright notice,
 *   this list of conditions and the following disclaimer in the documentation
 *   and/or other materials provided with the distribution.
 *
 * * Neither the name of Sensirion AG nor the names of its
 *   contributors may be used to endorse or promote products derived from
 *   this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */
#include <Arduino.h>
#include <SensirionI2cSbn4x.h>
#include <Wire.h>

// macro definitions
// make sure that we use the proper definition of NO_ERROR
#ifdef NO_ERROR
#undef NO_ERROR
#endif
#define NO_ERROR 0

SensirionI2cSbn4x sensor;

static char errorMessage[64];
static int16_t error;

void setup() {

    Serial.begin(115200);
    while (!Serial) {
        delay(100);
    }
    Wire.begin();
    sensor.begin(Wire, SBN4X_I2C_ADDR_20);

    int8_t productName[32] = {0};
    int8_t productType[10] = {0};
    int8_t serialNumber[32] = {0};
    error = sensor.getProductName(productName, 32);
    if (error != NO_ERROR) {
        Serial.print("Error trying to execute getProductName(): ");
        errorToString(error, errorMessage, sizeof errorMessage);
        Serial.println(errorMessage);
        return;
    }
    Serial.print("productName: ");
    Serial.print((const char*)productName);
    Serial.println();
    error = sensor.getProductType(productType, 10);
    if (error != NO_ERROR) {
        Serial.print("Error trying to execute getProductType(): ");
        errorToString(error, errorMessage, sizeof errorMessage);
        Serial.println(errorMessage);
        return;
    }
    Serial.print("productType: ");
    Serial.print((const char*)productType);
    Serial.println();
    error = sensor.getSerialNumber(serialNumber, 32);
    if (error != NO_ERROR) {
        Serial.print("Error trying to execute getSerialNumber(): ");
        errorToString(error, errorMessage, sizeof errorMessage);
        Serial.println(errorMessage);
        return;
    }
    Serial.print("serialNumber: ");
    Serial.print((const char*)serialNumber);
    Serial.println();
    error = sensor.startPeriodicMeasurementMode(30000);
    if (error != NO_ERROR) {
        Serial.print(
            "Error trying to execute startPeriodicMeasurementMode(): ");
        errorToString(error, errorMessage, sizeof errorMessage);
        Serial.println(errorMessage);
        return;
    }
    delay(200);
}

void loop() {

    uint32_t measurementCounter = 0;
    float o2DryPercent = 0.0;
    float co2DryPercent = 0.0;
    float pressure = 0.0;
    float o2PartialPressure = 0.0;
    float h2oPartialPressure = 0.0;
    float temperature = 0.0;
    float relativeHumidity = 0.0;
    SBN4xValidFlags flags = {flags.value = 0u};
    sensor.readMeasurements(measurementCounter, o2DryPercent, co2DryPercent,
                            pressure, o2PartialPressure, h2oPartialPressure,
                            temperature, relativeHumidity, flags);
    Serial.print("measurementCounter: ");
    Serial.print(measurementCounter);
    Serial.print("\t");
    Serial.print("o2DryPercent: ");
    Serial.print(o2DryPercent);
    Serial.print("\t");
    Serial.print("co2DryPercent: ");
    Serial.print(co2DryPercent);
    Serial.print("\t");
    Serial.print("pressure: ");
    Serial.print(pressure);
    Serial.print("\t");
    Serial.print("o2PartialPressure: ");
    Serial.print(o2PartialPressure);
    Serial.print("\t");
    Serial.print("h2oPartialPressure: ");
    Serial.print(h2oPartialPressure);
    Serial.print("\t");
    Serial.print("temperature: ");
    Serial.print(temperature);
    Serial.print("\t");
    Serial.print("relativeHumidity: ");
    Serial.print(relativeHumidity);
    Serial.print("\t");
    Serial.print("flags: ");
    Serial.print(flags.value);
    Serial.println();
}
